name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt update
        sudo apt install llvm-9 clang-9 lld-9 make
        sudo ln -sf /usr/bin/clang-9 /usr/local/bin/clang
        sudo ln -sf /usr/bin/lld-link-9 /usr/local/bin/lld-link
        sudo ln -sf /usr/bin/llvm-mc-9 /usr/local/bin/llvm-mc
    - name: Build
      run: |
        make
